### ISSUE TITLE
Support for Generators

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/tasklets#11]
Can we do support for generators? I feel like to support generators we should ideally have native support for async generators in Chrome... 

cc @bfgeek

**Comment by jamiemccrindle** [comment]
It would be great to have support for these:

https://github.com/tc39/proposal-async-iteration

**Comment by surma** [comment]
[Comlink](https://github.com/GoogleChromeLabs/comlink) has support for Async Generators. I plan to move the polyfill to use Comlink, so once that lands we are good to go here :)

**Comment by surma** [comment]
Now supported in the polyfill
